# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  

  build:
    desc: build go
    cmds:
      - go mod tidy
      - env GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags lambda.norpc -ldflags="-s -w" -o ../dist/bootstrap main.go
      - chmod +x ../dist/bootstrap
      - cd ../dist && zip bootstrap.zip bootstrap
    sources:
      - ./*.go
      - main/*.go
      - Taskfile.yml
    generates:
      - ../dist/main
    silent: true

  fastdeploy:
    desc: Deploy only lambda
    deps: [build]
    vars:
      FN:      
        sh: aws ssm get-parameter --name "hello-al2" --query "Parameter.Value" --output text
    cmds:
      - aws lambda update-function-code --function-name  {{.FN}} --zip-file fileb://../dist/bootstrap.zip

  test:
    desc: all go test
    cmds:
      - go test . 
