# https://taskfile.dev

version: '3'

vars:
  DIST: ../dist
  APP: fetchreport

tasks:
  run:
    desc: demo run
    cmds:
      - go run main/main.go --lambda hello-node

  build:
    desc: Build
    cmds:
      - mkdir -p {{.DIST}}
      - go build -o {{.DIST}}/{{.APP}} main/main.go
