library(readr)
library(ggplot2)
speedIn <- read.csv("./data/benchmark.csv", sep = ",", header = TRUE)
speed <- transform(speedIn, lang = as.character(Lang), speed=(Duration))
ggplot(speed, aes(y= speed, x=lang)) + geom_boxplot()
png(filename="fibcompare.png")
ggplot(speed, aes(y= speed, x=lang)) + geom_boxplot()
dev.off()
dev.off()
