# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

tasks:


  build:
    desc: build lambda
    cmds:
      -  mvn compile dependency:copy-dependencies -DincludeScope=runtime
    silent: true

