# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build-linux:
    desc: "Building go for linux"
    cmds:
      - env GOOS=linux go build -ldflags="-s -w" -o dist/linux/cfn-count main/main.go
    silent: true

  build:
    desc: "Building go"
    cmds:
      - go build -ldflags="-s -w" -o dist/cfn-count main/main.go
    silent: true

  test:
    desc: go unit tests
    cmds:
      - go test

  run:
    desc: Run counter
    cmds:
      - go run main/main.go
