sequenceDiagram
    participant S as Stack
    participant I as Instances   
    participant B as Data Bucket
    participant D as Deployment Bucket
    participant L as SelfDestructLambda
    S ->>L: Creates
    S ->>I: Creates
    D ->>I: load apps
    I ->>I: perform benchmark
    I ->>B: save benchmark
    I ->>I: Stop
    L ->> S: Timout-Delete