# https://taskfile.dev

version: '2'

env:
  AWS_DEFAULT_REGION: eu-central-1
  
vars:  
  VPC: BenchstanceVPCStack
  EC2: BenchstanceStack

tasks:


  test:
    desc: run test
    deps: [build]
    cmds:
      - npm test
  update:
    desc: install latest cdk and other modules
    cmds:
      - ncu -u
      - npm install

  deploy:
    desc: deploy stack without asking
    deps: [build]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk deploy {{.EC2}} --require-approval never --profile $AWSUME_PROFILE 

  diff:
    desc: diff stack without asking
    deps: [build]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk diff --profile $AWSUME_PROFILE

  destroy:
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk destroy --force --profile $AWSUME_PROFILE

  edge-of-tomorrow:
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: destroy

  get-data:
    desc: Load data from bucket
    dir: data
    vars: 
      bucket:
        sh: aws cloudformation list-exports --query 'Exports[?Name==`benchdata`].Value' --output text
    cmds:
      - aws s3 sync s3://{{.bucket}} .


